AWSTemplateFormatVersion: '2010-09-09'
Description: Create an EC2 instance and install Apache HTTP server using cfn-init

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      ImageId: "ami-025fe52e1f2dc5044"  # Replace with a valid AMI ID for your region
      KeyName: "aug.pem"  # Replace with your EC2 key pair name
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource MyEC2Instance --region ${AWS::Region}
      Tags:
        - Key: Name
          Value: MyEC2Instance

  MyEC2InstanceMetadata:
    Type: 'AWS::CloudFormation::Init'
    Properties:
      config:
        packages:
          yum:
            httpd: []  # For Apache HTTP server
        services:
          sysvinit:
            httpd:
              enabled: 'true'
              ensureRunning: 'true'
        files:
          /etc/httpd/conf/httpd.conf:
            content: |
              ServerRoot "/etc/httpd"
              Listen 80
              LoadModule dir_module modules/mod_dir.so
              DocumentRoot "/var/www/html"
              <Directory "/var/www/html">
                  AllowOverride None
                  Require all granted
              </Directory>
              <IfModule dir_module>
                  DirectoryIndex index.html
              </IfModule>
            mode: '000644'
            owner: root
            group: root


