Resources:
  MyInstance:
    Type: "AWS::EC2::Instance"
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          default:
            - setup
        setup:
          packages:
            yum:
              httpd: []
              git: []
              vim: []
            pip:
              boto3: []
              requests: []
          files:
            "/var/www/html/index.html":
              content: |
                <html>
                  <body>
                    <h1>Welcome to my website</h1>
                  </body>
                </html>
              mode: "000644"
              owner: "root"
              group: "root"
          services:
            sysvinit:
              httpd:
                enabled: "true"
                ensureRunning: "true"
    Properties:
      ImageId: "ami-025fe52e1f2dc5044"
      InstanceType: "t2.micro"
      UserData:
        Fn::Base64: |
          #!/bin/bash
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource MyInstance --region ${AWS::Region}