AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This template creates VPC in ap-south-1 region
  Author: Murali
  Company: Havik
Resources:
  MyCfnVPC:
    Type: AWS::EC2::VPC
    Properties:
       CidrBlock: "10.0.0.0/16"
       Tags:
       - Key: Name
         Value: MyVPC
       - Key: Env 
         Value: Prod
       - Key: Department
         Value: DevOps
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: vpc-0caed34b967ec192e
      CidrBlock: "10.0.1.0/24"
      AvailabilityZone: ap-south-1a
      Tags:
        - Key: Name
          Value: PublicSubnet1         